### ISSUE TITLE
findDependencies ends with Unexpected token error if file contains import keyword

### ISSUE THREAD

**Issue by MilanLempera** [klei/ng-dependencies#10]
You can reproduce error with this test

```
  it('should ignore import in source', function () {
    var source = 'import angular from "angular";\n' +
        'angular.module("test", []);';

    var deps = {
      dependencies: ['ng'],
      modules: {
        'test': []
      }
    };
    lookup(source).should.eql(deps);
  });
```

result is _Unexpected token_ error from esprima.

Esprima support ES6 modules, but you must use option sourceType in parse method options. 

```
esprima.parse(source, {sourceType: "module"})
```

I can send pull request with fix (simply add this option to esprima.parse, or make it configurable by findDependencies options), and import will be ignored - but is it intended behavior?

**Comment by blai** [comment]
ignoring import should be fine.
