### ISSUE TITLE
window.angular.module("foo") not understood.

### ISSUE THREAD

**Issue by SyntaxRules** [klei/ng-dependencies#8]
Thanks for the great work on this plugin. 

`angular.module("foo");` syntax works great.

`window.angular.module("foo");` syntax does not work.

I couldn't find any documentation on the fact so I ran your tests with `window` in front. Here are the tests:

```javascript
   it('should capture simple module declaration with window', function () {
    var source = 'window.angular.module("test", []);';
    var deps = {
      dependencies: ['ng'],
      modules: {
        'test': []
      }
    };
    lookup(source).should.eql(deps);
  });

  it('should capture the module dependencies with window', function () {
    var source = 'window.angular.module("test", ["one"]);';
    var deps = {
      dependencies: ['ng', 'one'],
      modules: {
        'test': ['one']
      }
    };
    lookup(source).should.eql(deps);
  });

    it('should capture module dependencies at root level with window', function () {
    var source = 'window.angular.module("test");\nwindow.angular.module("another").controller("Ctrl", ["$scope", function ($scope) {}]);';
    var deps = {
      dependencies: ['ng', 'test', 'another'],
      modules: {}
    };
    lookup(source).should.eql(deps);
  });
```

All three tests failed. (Can give output if desired)

Is it possible to get this functionality added? How hard is it? I did a quick check on the code and it looks like the `isAngularModuleStatement` just needs to be changed. I might attempt a pull request.

**Comment by joakimbeng** [comment]
It probably is possible, but why do you actually do this?

Why not just drop the `window.`?

**Comment by SyntaxRules** [comment]
I was working with someone troubleshooting a problem they were having with dependencies. Turned out to be this `window.`.

I asked the same question and they said visual studio doesn't like it when they do just `angular.module...` so they write `window.angular.module...`. I'll happily drop the `window.` for myself. Just looking to be a good contributor and add in the problem use case I found.

**Comment by blai** [comment]
Adding support for `window.angular.module` would increase the processing time for everybody else who just use `angular.module`. That's because now we need to look for two patterns instead of one. My suggestion for your case is to wrap your angular code in IIFE, like so:

```
(function (angular) {
    angular.module(...)
    ...
})(window.angular);
```

**Comment by joakimbeng** [comment]
I'm with @blai on this. Closing.
